apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dotnet-greeting-api-dev
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/dotnet_greeting_api/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps-gitops
  validation: client
  targetNamespace: greeting-apis
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: dotnet-api
      namespace: greeting-apis
